# Copyright (C) 2015-2024 IoT.bzh Company
# Author: José Bollo <jose.bollo@iot.bzh>
#
# SPDX-License-Identifier: LGPL-3.0-only

.PHONY: all clean

all clean:
	$(MAKE) -C v3 $(MAKECMDGOALS)
	$(MAKE) -C v4 $(MAKECMDGOALS)

